apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-consumer
  namespace: development
  labels:
    app: spring-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-consumer
  template:
    metadata:
      labels:
        app: spring-consumer
      annotations:
        dapr.io/enabled: "True"
        dapr.io/app-id: "spring-consumer"
        dapr.io/app-port: "9091"
        dapr.io/enable-api-logging: "True"
        dapr.io/sidecar-cpu-request: "0.1"
        dapr.io/sidecar-memory-request: "250Mi"
        dapr.io/sidecar-cpu-limit: "0.3"
        dapr.io/sidecar-memory-limit: "1000Mi"
        dapr.io/config: "tracing"
        dapr.io/log-as-json: "True"
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "debug"
        dapr.io/enable-app-health-check: "True"
        dapr.io/app-health-check-path: "/api/health"
        dapr.io/app-health-probe-interval: "30"
        dapr.io/app-health-probe-timeout: "200"
        dapr.io/app-health-threshold: "2"
    spec:
      containers:
        - name: spring-consumer
          image: docker.io/library/spring-consumer:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9091
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /api/health
              port: 9091
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
          resources:
            requests:
              cpu: "0.1"
              memory: 256Mi
            limits:
              cpu: "0.5"
              memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: spring-consumer
  namespace: development
spec:
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: spring-consumer
  sessionAffinity: None
  type: NodePort