apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-performance-b
  namespace: development-performance-non-dapr
  labels:
    app: spring-performance-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-performance-b
  template:
    metadata:
      labels:
        app: spring-performance-b
    spec:
      containers:
        - name: spring-performance-b
          image: docker.io/library/spring-performance-b:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9081
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9081
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /api/health
              port: 9081
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
          resources:
            requests:
              cpu: "0.2"
              memory: 256Mi
            limits:
              cpu: "0.5"
              memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: spring-performance-b
  namespace: development-performance-non-dapr
spec:
  ports:
    - port: 9081
      targetPort: 9081
      protocol: TCP
  selector:
    app: spring-performance-b
  sessionAffinity: None
  type: NodePort