apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service-producer
  namespace: development
  labels:
    app: spring-service-producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-service-producer
  template:
    metadata:
      labels:
        app: spring-service-producer
      annotations:
        dapr.io/enabled: "True"
        dapr.io/app-id: "spring-service-producer"
        dapr.io/app-port: "9080"
        dapr.io/enable-api-logging: "True"
        dapr.io/sidecar-cpu-request: "0.1"
        dapr.io/sidecar-memory-request: "128Mi"
        dapr.io/sidecar-cpu-limit: "0.3"
        dapr.io/sidecar-memory-limit: "256Mi"
        dapr.io/env: "GOMEMLIMIT=900MiB"
        dapr.io/config: "tracing"
        dapr.io/log-as-json: "True"
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "debug"
        dapr.io/enable-app-health-check: "True"
        dapr.io/app-health-check-path: "/api/health"
        dapr.io/app-health-probe-interval: "30"
        dapr.io/app-health-probe-timeout: "200"
        dapr.io/app-health-threshold: "2"
    spec:
      containers:
        - name: spring-service-producer
          image: docker.io/library/spring-service-producer:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /api/health
              port: 9080
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
          resources:
            requests:
              cpu: "0.1"
              memory: 125Mi
            limits:
              cpu: "0.3"
              memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: spring-service-producer
  namespace: development
spec:
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    app: spring-service-producer
  sessionAffinity: None
  type: NodePort