apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency
  namespace: development-performance-dapr
scopes:
  - spring-performance-a
  - spring-performance-b
spec:
  policies:

    timeouts:
      general: 3s
      important: 5s
      largeResponse: 6s

    retries:
      DefaultRetryPolicy:
        policy: constant
        duration: 1s
        maxRetries: 3

      fastRetries:
        policy: constant
        duration: 10ms
        maxRetries: 3

      retryForever:
        policy: exponential
        maxInterval: 10s
        maxRetries: -1

    circuitBreakers:
      serviceToServiceCB:
        maxRequests: 100
        interval: 8s
        timeout: 45s
        trip: consecutiveFailures > 8

  targets:
  
    apps:
      spring-performance-a:
        timeout: general
        retry: DefaultRetryPolicy
        circuitBreaker: serviceToServiceCB

      spring-performance-b:
        timeout: important
        retry: DefaultRetryPolicy
        circuitBreaker: serviceToServiceCB