apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.9.0
    replicas: 3 # you can increase it for more broker replica 
    listeners:
      - name: minikube
        port: 9094
        type: internal
        tls: false
        configuration:
          brokers:
            - broker: 0
              advertisedHost: 127.0.0.1
              advertisedPort: 19094
            - broker: 1
              advertisedHost: 127.0.0.1
              advertisedPort: 19095
            - broker: 2
              advertisedHost: 127.0.0.1
              advertisedPort: 19096
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 1
      default.replication.factor: 3
      min.insync.replicas: 3
      inter.broker.protocol.version: "3.9"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 3 # you can increase it for more ZK replica
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-0
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: my-cluster-kafka-0
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka
    strimzi.io/pool-name: kafka
  ports:
    - protocol: TCP
      port: 19094
      targetPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-1
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: my-cluster-kafka-1
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka
    strimzi.io/pool-name: kafka
  ports:
    - protocol: TCP
      port: 19095
      targetPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-2
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: my-cluster-kafka-2
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka
    strimzi.io/pool-name: kafka
  ports:
    - protocol: TCP
      port: 19096
      targetPort: 9094
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3