apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitScheduler
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 15s"
  - name: direction
    value: "input"
scopes:
 - spring-service-scheduler