apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: messagepubsub
spec:
  topic: messages
  routes: 
    default: /consumeDaprSdk
  pubsubname: messagepubsub
  deadLetterTopic: dl-messagepubsub
  metadata:
    maxPriority: 3
    queueType: quorum
scopes:
 - spring-service-producer
 - spring-service-consumer